<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-T8V1FV5L" name="testng.Invocation" tests="6" failures="0" timestamp="20 Mar 2021 08:18:16 GMT" time="5.074" errors="1">
  <testcase name="test1" time="0.006" classname="testng.Invocation"/>
  <testcase name="test1" time="0.003" classname="testng.Invocation"/>
  <testcase name="test1" time="0.006" classname="testng.Invocation"/>
  <testcase name="test1" time="0.030" classname="testng.Invocation"/>
  <testcase name="test1" time="0.003" classname="testng.Invocation"/>
  <testcase name="test2" time="5.026" classname="testng.Invocation">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method org.testng.internal.TestNGMethod.test2() didn&#039;t finish within the time-out 5000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.test2() didn't finish within the time-out 5000
	at java.util.concurrent.ThreadPoolExecutor.runStateLessThan(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.processWorkerExit(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- test2 -->
</testsuite> <!-- testng.Invocation -->
